name: Actions
runs-on: push:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: make setup
    - name: start
      run: make start
    - name: tests
      run: make tests
    - name: linter
      run: make lint

    