name: Actions
on:
  # на push и pull_request, только для ветки master
  push:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: make setup
    - name: start
      run: make start
    - name: tests
      run: make tests
    - name: linter
      run: make lint

    