name: Actions
on:
  # на push и pull_request, только для ветки master
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup
        run: make setup
      - name: tests
        run: make tests
      - name: linter
        run: make lint
        env:
          SNYK_TOKEN: ${{ ca8ebf9d-e57a-427f-af25-b3b6a1656bb6 }}

    